version: '3.4'

services:
  reversimvcapp:
    image: ${DOCKER_REGISTRY-}reversimvcapp
    build:
      context: .
      dockerfile: ReversiMvcApp/Dockerfile
    depends_on:
      - reversirestapi
    ports:
      - "80"
      - "443"
    environment:
      SQLSource: "mssql"
      SQLPass: "U4zgsHysuJ8"
      APISource: "reversirestapi"
      APIUrl: "http://localhost:5001/api/"
      Environment: "Development"

  reversirestapi:
    image: ${DOCKER_REGISTRY-}reversirestapi
    build:
      context: .
      dockerfile: ReversiRestAPI/Dockerfile
    depends_on:
      - mssql
    ports:
      - "5001:80"
    environment:
      SQLSource: "mssql"
      SQLPass: "U4zgsHysuJ8"

  mssql:
    container_name: mssql
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "U4zgsHysuJ8"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
