name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ReversiBackend.sln
    - name: Build
      run: dotnet build ReversiBackend.sln --no-restore
    - name: Test
      run: dotnet test ReversiBackend.sln --no-build --verbosity normal
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: docker login -u paulrill -p $DOCKER_PASSWORD
    - name: Build Api Image
      run: docker build -f Dockerfile.api -t paulrill/reversi:api .
    - name: Build Backend Image
      run: docker build -f Dockerfile.backend -t paulrill/reversi:backend .
    - name: Build Latest Image
      run: docker build -f Dockerfile.latest -t paulrill/reversi:latest .
    - name: Push API image
      run: docker push paulrill/reversi:api
    - name: Push Backend image
      run: docker push paulrill/reversi:backend
    - name: Push Latest image
      run: docker push paulrill/reversi:latest
    - name: Restart API Docker Container
      env:
        API_PORTAINER_URL: ${{ secrets.API_PORTAINER_URL }}
      run: curl --location --request POST $API_PORTAINER_URL
    - name: Restart MVC Docker Container
      env:
        MVC_PORTAINER_URL: ${{ secrets.MVC_PORTAINER_URL }}
      run: curl --location --request POST $MVC_PORTAINER_URL
      
